apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - cluster-role-binding.yaml
  - cluster-role.yaml
  - config-map.yaml
  - custom-resouce-definitions.yaml
  - deployment.yaml
  - role-binding.yaml
  - role.yaml
  - secret.yaml
  - service-account.yaml
  - service.yaml
