---
- name: Apt
  become: yes
  block:
    - name: apt update
      apt:
        update_cache: yes
        cache_valid_time: "{{ homeLab.apt.cache_valid_time }}"
    - name: Install packages via Apt
      apt:
        state: present
        pkg:
          - nfs-server
    - name: Set /etc/exports
      ansible.builtin.template:
        src: files/etc/exports.j2
        dest: /etc/exports
        backup: yes
    - name: Enable service nfs-server
      ansible.builtin.systemd:
        name: nfs-server
        state: started
        enabled: yes
