---
- name: Configure kubeadm and kubelet
  become: yes
  block:
  - name: Check for kubeadm
    register: check_kubeadm
    ansible.builtin.stat:
      path: /etc/kubernetes/admin.conf
  - name: Initialize kubeadm
    when: not check_kubeadm.stat.exists
    ansible.builtin.shell:
      cmd: kubeadm init --pod-network-cidr=10.0.0.0/16
  # TODO: kubectl taint nodes --all node-role.kubernetes.io/control-plane-
  # TODO: if no check
  - name: Install Calico
    ansible.builtin.shell:
      cmd: kubectl apply -f https://projectcalico.docs.tigera.io/manifests/calico.yaml
  - name: Enable service kubelet
    ansible.builtin.systemd:
      name: kubelet
      state: started
      enabled: yes
