---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-scripts
data:
  backup.sh: |
    #!/bin/bash -Ceuo pipefail

    export DEBIAN_FRONTEND=noninteractive
    apt-get update -qq
    apt-get install -qq --no-install-recommends expect openssh-client >/dev/null

    echo "Connecting $BACKUP_USERNAME@$BACKUP_HOSTNAME"
    expect <<EOF >/tmp/result.txt
    set timeout 10
    spawn ssh $BACKUP_USERNAME@$BACKUP_HOSTNAME
    expect "(yes/no"
    send "yes\r"
    expect "password: "
    send "$BACKUP_PASSWORD\r"
    expect "> "
    send "show config\r"
    expect "> "
    send "exit\r"
    expect eof
    EOF

    sed -n '/> show config/,/> exit/{/> show config/!{/> exit/!p}}' /tmp/result.txt
