---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-scripts
data:
  backup.yaml: |
    ---
    - hosts: all
      connection: network_cli
      vars:
        ansible_network_os: yamaha_network.rtx.rtx
      tasks:
        - name: get configuration
          yamaha_network.rtx.rtx_command:
            commands:
            - show config
          register: result
        - name: Copy output to file
          ansible.builtin.copy:
            content: "{{ result.stdout[0] }}"
            dest: "config.txt"
        - name: Print config
          ansible.builtin.debug:
            msg:
              - "{{ result.stdout[0] }}"
