---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wordpress
resources:
  - sealed-secret.yaml
patches:
  - path: deployment.yaml
    target:
      kind: Deployment
      name: wordpress
      namespace: wordpress
