---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: effortless-credentials
spec:
  encryptedData:
    password: AgCKpB4MghGFQphbXJa8wLSkImh7rk5fVYs38ZlynpyXXel9fifpWdMUTChf4DuK1xK+pvyp7p8ku6Kxhum/glsiAA9q/WFNBmtagHPDZot3dlCh9Vvd/w8beMmrpyC4/A0E4C4Z4bmO/EqoXVsT/gcG1Zjq9jmb4okETqqtCnOIHzTY9k7n0vaMPa7mgKsjtEnmgV5YRf0PEJ6W8B/Y9/WqZXzK1SjF0QMWNe8J81bSl2NgEVv0AUOf8V8CC8Dw4Y2PenkvyOACWvBclCG62B5ZVseakp+Z87S55XXhQQkIuc3AtybCQhctaG0hPGoG9h1OW8X92U0fsBjyD884XA64hC2gadAcRaifGz8yoBVBcpJe4ky1H6e4LNNeTWh6zeNP+HK+F6+6jkgfDDuW0kmCTJcH3psCzOBM4AcwEZrcnAkjikgRjA8vvpUD0N1Yueuzx5Y3ugiqmXaTh5STvdjF3OGoywR5fLPwuPQrv/9Fn9EL0GdHKbZzb0veC+9KhloHLn42uTzDFJfLivG/6UotD21bdGxfnLPZBYsXUOSJOnf5agXJBl1WakMrqk05RDdwae1xxyy4iuIaT+74CU0XlxAEEqCRGNolUdrjnmVfQIPSC1VWlUglIw+iQNKXQL6Ca5lD1AWkEDjWUAjgZS81npoj7Dr/Q+7D3uVr1q+7hOBJotIdDxmNEDReT54HlOugo1nhH9T5KdqSSRoaD5jvOENEdsvpL7KAznb3o8+vfi/nQ8OURSMNrb3wPi0MWELDI/4dF7GKVj44pP3vV6+eII5OuRz3DuU=
    postgres-password: AgBc2hFJJCaP3qzq2r22Wx/vFFvonjo8pxdvlwM8m+ecnNULB8QlRWL6+evuiori4KHD07qCrVG+V0OX3rhKJXNi7MojsHOYsa5JJj2PZzWU6TnmtW9I0rZvWXNc51teltG/2q4N7VCYKFj2OTu3D4hzVijl/0q5v/9CFOIOOZTHlIOQ7uIjaWGCUwStEP0+0LNs80WSQDuJQkqh0ZQV7hpTJDXHHOhgkZvD10+k/S22wec7+CiANHCot8UN//qzoQgbQGQU1hum+h/8rXuCEXZFwWvCD5WcUBf5obBmKxbF/rkTP5zt8YkPKQ7kbStbMx79Agi4z6+hv6twz0s+AdAc1lPiQia7QqfOj2X+/SAvAQoqBJT2PyndDZj0+0PBH5RaIYAY1M6AzxTuc9ciCfQnn9cSdqGLSNjfr/ZOWXQBCD+leE8LawpCIdm2isJveMScniGgUKA93Ob89TN4jsWg+4WU1dOnEe+zCBfvux64vSzppqpLQo8/WFa4UHPgbS2MjiHwFWs5dwfZBFtiisQz6rUfoA/RLcgvri6hpUBXQnu3+kybYv+D5fMzge9/ev/mnDZB2+1FoZZhHHlRdt6qVZ0ePVuimjIoSk6mp1my9H9Qjihrcb5tXHTs9pCWls8mAshFDx3uPJGp7mrWZiYQ7ppgGMS7jYDGK8MQGlZ9Zvqw5HJzByIg3RfHYmOwhEFlnDl147ta/d9PQUnqbP2+ZKdcB4S3dR4DBrg/FQ67oxD42Mz+nOHGeNUbZTM6Xl+yXtYc2zAgOJNIVhc3X0rvc6oshiZmC4A=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: effortless-credentials
    type: Opaque
