---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: effortless-credentials
spec:
  encryptedData:
    postgresql-password: AgAxXKUdqbQAeMWTFCiCidtvrZThCMcg5p2zIqiVuE+MHKBIDFsvxGoQVycFPmFK48qsLLuMisezpgmJjadP6C3XPC3Puktm1jQ5WM3yIIv/6ps52w8n2GaeyVlUcg5U6MCEFtR8m9K656emJuRX8nP+dqQ1abJuiXa6FBzgxg6VAYXhYZa2U0yHcuBmgITTUzE9p81Z93yfuPVgCcN5qwpy4CuOr1Xb0xvEiq/jg0wlQk0WN7Ug/3E5iToHEq4tAiM6yzMYIHub2hpR+LPuhSZ94Y5asH8QFwil7rPTFHCr84A2xNVjjQCcRwzFyFFSIsaMAkDS5KZz31R87Brao8xLlq2cAYRuRYxw0bM45eXlK21MSaKNACLhdwkUI9f30yJihx1Ykv5TToc8NlWa88vuJvg/EDex5rGXj0fgk7eRhY47aAciYqYvcJOejD5Pd2Zny1bec1/tA9epXyFzAAjcUSFDEO/8sgMmBtQZZ5yvtqP+k3jgsPpiCJpCS2FbEDtrQfqjEEoj3MuMEYVFlLpnGOd17Ggv8lpXWM4NbqLCzO0JU+iA4EaObvjPckR29fQITY+sQ57+8z3+ME+p7pKSJA2bNnjQYvWIVT6MIsipLreghmQPO2VGL1qBoFnZWphR/e0b6yyMAf/BKwOeYDrzg4ylAKMujHNG+mtLaNMpZxydU0gLbCP2QNoxGM+JeYSCyl2caZdGhfIZY4Z/2+m28uJHxw1yvuB6nEaL4QBLdpWZzT91A8ptv+plwV1CtnKUPANnCWAn8HiODbUz3OB0P0EuUi8a0gA=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: effortless-credentials
    type: Opaque
