apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: owncloud-server
  labels:
    app.kubernetes.io/component: owncloud-server
    app.kubernetes.io/name: owncloud-server
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "20G"
spec:
  rules:
    - host: owncloud.local
      http:
        paths:
          - backend:
              serviceName: owncloud-server
              servicePort: http
