apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: owncloud
commonLabels:
  app.kubernetes.io/instance: owncloud
  app.kubernetes.io/part-of: owncloud
  app.kubernetes.io/managed-by: argocd
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- sealed-secrets.yaml
