---
apiVersion: v1
kind: Service
metadata:
  name: n8n
  labels:
    app.kubernetes.io/name: n8n
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: n8n
  ports:
    - name: http
      port: 5678
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app.kubernetes.io/name: postgres
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
  selector:
    app.kubernetes.io/name: postgres