---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: revealer
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: revealer
          image: ghcr.io/corrupt952/revealer:v1.0.0@sha256:cbac66492ccb7313eaf134a50a1869ad715ecca0d4cc2e0682a4769523cc4ab8
          env:
            - name: PORT
              value: "8080"
          ports:
            - name: http
              containerPort: 8080
