---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: revealer
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: revealer
          image: ghcr.io/corrupt952/revealer:v1.0.0
          env:
            - name: PORT
              value: "8080"
          ports:
            - name: http
              containerPort: 8080
