grafana.ini:
  auth.anonymous:
    enabled: true
    org_name: 'Main Org.'
    org_role: Admin

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.prometheus.svc.cluster.local
        isDefault: true

dashboardproviders.yaml:
  apiVersion: 1
  providers:
  - name: 'default'
    orgId: 1
    folder: 'default'
    type: file
    disableDeletion: true
    editable: true
    options:
      path: /var/lib/grafana/dashboards/standard
dashboards:
  default:
    prometheus-stats:
      gnetId: 2
      revision: 2
      datasource: Prometheus
    CoreDNS:
      gnetId: 14981
      revision: 2
      datasource: Prometheus
    # Node Exporter Full:
    #   gnetId: 1860
    #   revision: 31
    # ArgoCD:
    #   gnetId: 14584
    #   revision: 1
