grafana.ini:
  auth.anonymous:
    enabled: true
    org_name: 'Main Org.'
    org_role: Admin

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: ttp://prometheus-server.prometheus.svc.cluster.local
        isDefault: true

dashboards:
  default:
    Node Exporter Full:
      gnetId: 1860
      revision: 31
    CoreDNS:
      gnetId: 14981
      revision: 2
    ArgoCD:
      gnetId: 14584
      revision: 1
