grafana.ini:
  auth.anonymous:
    enabled: true
    org_name: 'Main Org.'
    org_role: Admin

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.prometheus.svc.cluster.local
        isDefault: true

dashboardProviders:
 dashboardproviders.yaml:
   apiVersion: 1
   providers:
   - name: 'default'
     orgId: 1
     folder: ''
     type: file
     disableDeletion: false
     editable: true
     options:
       path: /var/lib/grafana/dashboards/default
dashboards:
  default:
    prometheus-stats:
      gnetId: 2
      revision: 2
      datasource: Prometheus
    CoreDNS:
      gnetId: 14981
      revision: 2
      datasource: Prometheus
    Node Exporter Full:
      gnetId: 1860
      revision: 31
      datasource: Prometheus
    # TODO: https://argo-cd.readthedocs.io/en/stable/operator-manual/metrics/
    # ArgoCD:
    #   gnetId: 14584
    #   revision: 1
    # TODO: https://github.com/corrupt952/sandbox/tree/main/docker/prometheus-grafana
    rtx1300:
      url: https://gist.githubusercontent.com/corrupt952/51a9a0668b7dc0079b84d09712eaf4a7/raw/9b36680b86cf52d5c8277e66ccefe0581fdbe22e/rtx1300.json
      datasource: Prometheus
