grafana.ini:
  auth.anonymous:
    enabled: true
    org_name: 'Main Org.'
    org_role: Admin

dashboards:
  NodeExporterFull:
    gnetId: 1860
    revision: 31
  CoreDNS:
    gnetId: 14981
    revision: 2
  ArgoCD:
    gnetId: 14584
    revision: 1
