global:
  storageClass: nfs-csi

replicaCount: 3
allowEmptyPassword: false
existingSecret: wordpress-credentials

persistence:
  accessModes:
    - ReadWriteMany

mariadb:
  enabled: false

memcached:
  enabled: false

externalDatabase:
  host: mariadb.wordpress.svc.cluster.local
  user: wordpress
  database: wordpress
  existingSecret: wordpress-credentials

service:
  type: ClusterIP

extraEnvVars:
  - name: PHP_UPLOAD_MAX_FILESIZE
    value: 1024M
  - name: PHP_POST_MAX_SIZE
    value: 1024M
  - name: PHP_MAX_EXECUTION_TIME
    value: "0"
  - name: PHP_MEMORY_LIMIT
    value: 2048M

extraVolumeMounts:
  - name: wordpress-credentials-ads-txt
    mountPath: /opt/bitnami/wordpress/ads.txt
    subPath: ads.txt
    readOnly: true

extraVolumes:
  - name: wordpress-credentials-ads-txt
    secret:
      secretName: wordpress-credentials
      items:
        - key: ads.txt
          path: ads.txt
