---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - path: manifests/cloudflared/base
    repoURL: https://github.com/corrupt952/home
    targetRevision: develop/cloudflared-daemon-set # FIXME:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
