---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: descheduler
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - ref: home
      repoURL: https://github.com/corrupt952/home
    - chart: descheduler
      repoURL: https://kubernetes-sigs.github.io/descheduler/
      targetRevision: 0.30.1
      helm:
        releaseName: descheduler
        valueFiles:
          - $home/manifests/values/descheduler.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
