---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: effortless
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - ref: home
      repoURL: https://github.com/corrupt952/home
    - path: manifests/effortless/base
      repoURL: https://github.com/corrupt952/home
    - chart: postgresql
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 12.8.0
      helm:
        releaseName: postgresql
        valueFiles:
        - $home/manifests/values/postgresql.yaml
    - chart: redis
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 17.14.4
      helm:
        releaseName: redis
        valueFiles:
        - $home/manifests/values/redis.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: effortless
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
