---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
# Core
- nfs-subdir-external-provisioner.yaml
- calico.yaml
- sealed-secrets.yaml
- cloudflared.yaml
- descheduler.yaml
# Monitoring
- metrics-server.yaml
- prometheus.yaml
- grafana.yaml
# Argo
- argo-cd.yaml
- argo-events.yaml
- argo-workflows.yaml
# Home Automation
- networks.yaml
# Services
- wordpress.yaml
- revealer.yaml
- effortless.yaml
