---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  # Core
  - csi-driver-nfs.yaml
  - calico.yaml
  - sealed-secrets.yaml
  - cloudflared.yaml
  - descheduler.yaml
  # Monitoring
  - metrics-server.yaml
  - kubernetes-dashboard.yaml
  # - prometheus.yaml
  # - grafana.yaml
  # Argo
  - argo-cd.yaml
  - argo-events.yaml
  - argo-workflows.yaml
  # Virtual machine
  - kubevirt.yaml
  - cdi.yaml
  # Home Automation
  - networks.yaml
  # Services
  - wordpress.yaml
  - revealer.yaml
  - n8n.yaml
