---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - ref: home
      repoURL: https://github.com/corrupt952/home
    - chart: prometheus
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 25.30.0
      helm:
        releaseName: prometheus
        valueFiles:
          - $home/manifests/values/prometheus.yaml
    - chart: prometheus-snmp-exporter
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 5.6.0
      helm:
        releaseName: prometheus-snmp-exporter
        valueFiles:
          - $home/manifests/values/prometheus-snmp-exporter.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: prometheus
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
