name: Build and Ship

on:
  push:
    branches:
      - main

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - id: set-matrix
        run: |
          matrix=$(jq -ncR '[inputs]' <<< $(ls containers))
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  build_and_ship:
    runs-on: ubuntu-latest
    needs: set-matrix
    strategy:
      matrix:
        container: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: "containers/${{ matrix.container }}"
          push: true
          tags: |-
            ghcr.io/corrupt952/home/${{ matrix.container }}:${{ github.sha }},
            ghcr.io/corrupt952/home/${{ matrix.container }}:latest
